import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });


import GameChat from '@/components/gameChat'
import GamePlayer from '@/components/gamePlayer'


export const metadata: Metadata = {
  title: "Scribble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        
        <GamePlayer/>
        {children}
        <GameChat/>
      
      </body>
    </html>
  );
}
