import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });


import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: "Scribble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div className="flex flex-col justify-center items-center">
      
      <NavBar/>
      {
        children
      }
    
    </div>
  );
}
