import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });


import GameChat from '@/components/gameChat'
import GamePlayer from '@/components/gamePlayer'


export const metadata: Metadata = {
  title: "Scribble",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: {
    game: string
  }
}>) {
  
  return (
    <div className="flex justify-between p-24">
      
      <GamePlayer/>
      {children}
      <GameChat userName={params.game}/> 
    
    </div>
  );
}
